 control_node:
   ros__parameters:
    path_topic: "/path"
    odom_topic: "/odom/filtered"
    cmd_vel_topic: "/cmd_vel"
    lookahead_distance: 1.5
    steering_gain: 1.5
    max_steering_angle: 0.5
    linear_velocity: 1.0